### ISSUE TITLE
增加对岛内链接的识别

### ISSUE THREAD

**Issue by WenqiOfficial** [yudanhezhongweijie/DawnIslandK#268]
请求增加对岛内链接的识别
如果是岛内的链接，可以直接在APP内跳转到对应的串（Or其它），而无需跳转至浏览器打开
(oﾟvﾟ)ノ

**Comment by fishballzzz** [comment]
感谢反馈。这个本来是有支持的。。可是安卓11还是12把设置改了所以得app这边再更新。。我找个时间研究一下
________________________________
From: WenqiOfficial ***@***.***>
Sent: Monday, August 1, 2022 11:02:54 PM
To: fishballzzz/DawnIslandK ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fishballzzz/DawnIslandK] 增加对岛内链接的识别 (Issue #268)


增加对岛内链接的识别
如果是岛内的链接，可以直接在APP内跳转到对应的串（Or其它），而无需跳转至浏览器打开
(oﾟvﾟ)ノ

**Comment by NHypocrite** [comment]
请求增加对岛内链接的识别 +

之前已经成功添加了nmbxd1.com，可是肥肥们在引用的链接还是习惯是nmbxd.com，希望把这个也添加到默认打开的链接里，就不用再跳转浏览器啦(*´∀`)

发现蓝岛倒是添加了好多可以打开的链接，截图在这里了，也许会有用？

**Comment by yudanhezhongweijie** [comment]
v1.6.12支持nmbxd.com
