### ISSUE TITLE
灌铅按钮提示 长图模糊 颜文字清后台重置 自定义顶栏图片截取范围不准确 查看引用串号无法获取原串

### ISSUE THREAD

**Issue by Tumbleweed1024** [yudanhezhongweijie/DawnIslandK#269]
跑团版中灌铅骰按钮彩蛋消息依旧是"ATM is watching you"
长图片点进去之后直接看是比原图模糊的，保存后不受影响
颜文字自定义点进去之后如果清后台强退会导致所有自定义过的颜文字丢失
自定义顶栏功能截取图片时预览的范围与实际显示的范围不一致(更小)
点击串内引用的串号，无法跳转到原串(这个算是新增功能建议)
赞美肥哥(ノﾟ∀ﾟ)ノ

**Comment by fishballzzz** [comment]
感谢反馈。

- 跑团版中灌铅骰按钮彩蛋消息依旧是"ATM is watching you"
   这个功能我需要和三酱确认一下才能启动

长图片点进去之后直接看是比原图模糊的，保存后不受影响
  可以给个具体的串号我排查吗？这个功能没出过问题，有没有可能单纯卡了？图片下载好了显示也得一些时间和资源

颜文字自定义点进去之后如果清后台强退会导致所有自定义过的颜文字丢失
    这个功能我这边没问题。有具体的复现步骤吗？另外，添加表情以后得退出编辑页面才会保存


自定义顶栏功能截取图片时预览的范围与实际显示的范围不一致(更小)
     这个说实话我不会修。。不然截图多截点？

点击串内引用的串号，无法跳转到原串(这个算是新增功能建议)
    有用1.6.06以上版本吗？

________________________________
From: Tumbleweed1024 ***@***.***>
Sent: Monday, August 15, 2022 6:29:27 AM
To: fishballzzz/DawnIslandK ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fishballzzz/DawnIslandK] 灌铅按钮提示 长图模糊 颜文字清后台重置 自定义顶栏图片截取范围不准确 查看引用串号无法获取原串 (Issue #269)


跑团版中灌铅骰按钮彩蛋消息依旧是"ATM is watching you"
长图片点进去之后直接看是比原图模糊的，保存后不受影响
颜文字自定义点进去之后如果清后台强退会导致所有自定义过的颜文字丢失
自定义顶栏功能截取图片时预览的范围与实际显示的范围不一致(更小)
点击串内引用的串号，无法跳转到原串(这个算是新增功能建议)
赞美肥哥(ノﾟ∀ﾟ)ノ

**Comment by Tumbleweed1024** [comment]
长图片点进去之后直接看是比原图模糊的，保存后不受影响
可以给个具体的串号我排查吗？这个功能没出过问题，有没有可能单纯卡了？图片下载好了显示也得一些时间和资源
例如串>>No.52690622，确定不是卡了，网络良好，效果见测试串>>No.52701009的>>No.52701942或附件1

颜文字自定义点进去之后如果清后台强退会导致所有自定义过的颜文字丢失
这个功能我这边没问题。有具体的复现步骤吗？另外，添加表情以后得退出编辑页面才会保存
丢失自定义表情的复现方式: 进入自定义颜文字界面，此时划掉后台，再次进入黎明岛自定义文字界面，之前自定义过的表情均会恢复默认

点击串内引用的串号，无法跳转到原串(这个算是新增功能建议)
有用1.6.06以上版本吗？
当前在用就是1.6.06，引用主串串号下方会有显示原串按钮，但是引用回串是无法跳转到原串的，见测试串>>No.52701009的>>No.52701043
另外，搜索里的跳转串好像也没法通过回串跳转，只能通过主串跳转( ﾟ∀。)7"
见附件2＆附件3

________________________________
发件人: fishballzzz ***@***.***>
发送时间: 2022年10月11日星期二 15:42
收件人: fishballzzz/DawnIslandK
抄送: Tumbleweed1024; Author
主题: Re: [fishballzzz/DawnIslandK] 灌铅按钮提示 长图模糊 颜文字清后台重置 自定义顶栏图片截取范围不准确 查看引用串号无法获取原串 (Issue #269)


感谢反馈。

- 跑团版中灌铅骰按钮彩蛋消息依旧是"ATM is watching you"
这个功能我需要和三酱确认一下才能启动

长图片点进去之后直接看是比原图模糊的，保存后不受影响
可以给个具体的串号我排查吗？这个功能没出过问题，有没有可能单纯卡了？图片下载好了显示也得一些时间和资源

颜文字自定义点进去之后如果清后台强退会导致所有自定义过的颜文字丢失
这个功能我这边没问题。有具体的复现步骤吗？另外，添加表情以后得退出编辑页面才会保存


自定义顶栏功能截取图片时预览的范围与实际显示的范围不一致(更小)
这个说实话我不会修。。不然截图多截点？

点击串内引用的串号，无法跳转到原串(这个算是新增功能建议)
有用1.6.06以上版本吗？

________________________________
From: Tumbleweed1024 ***@***.***>
Sent: Monday, August 15, 2022 6:29:27 AM
To: fishballzzz/DawnIslandK ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fishballzzz/DawnIslandK] 灌铅按钮提示 长图模糊 颜文字清后台重置 自定义顶栏图片截取范围不准确 查看引用串号无法获取原串 (Issue #269)


跑团版中灌铅骰按钮彩蛋消息依旧是"ATM is watching you"
长图片点进去之后直接看是比原图模糊的，保存后不受影响
颜文字自定义点进去之后如果清后台强退会导致所有自定义过的颜文字丢失
自定义顶栏功能截取图片时预览的范围与实际显示的范围不一致(更小)
点击串内引用的串号，无法跳转到原串(这个算是新增功能建议)
赞美肥哥(ノﾟ∀ﾟ)ノ

**Comment by yudanhezhongweijie** [comment]
串跳转的话必须引用串号本身才可以的，串的回复没有串首的信息也就没办法跳转了

**Comment by yudanhezhongweijie** [comment]
- 长图模糊的话可能是比较底层的问题，不一定能修。。等他读取后了重新打开会好点吗？

> 颜文字自定义点进去之后如果清后台强退会导致所有自定义过的颜文字丢失
这个是这样设计的，因为只有正常退出那个页面的时候才会保存

**Comment by Tumbleweed1024** [comment]
颜文字出现的问题不是本次自定义不保存，而是强退后之前自定义过的颜文字也会丢失，所有颜文字都会初始化
长图等待后清晰度未出现变化

________________________________
发件人: Weijie Zhong ***@***.***>
发送时间: Monday, January 16, 2023 4:53:24 AM
收件人: yudanhezhongweijie/DawnIslandK ***@***.***>
抄送: Tumbleweed1024 ***@***.***>; Author ***@***.***>
主题: Re: [yudanhezhongweijie/DawnIslandK] 灌铅按钮提示 长图模糊 颜文字清后台重置 自定义顶栏图片截取范围不准确 查看引用串号无法获取原串 (Issue #269)


  *   长图模糊的话可能是比较底层的问题，不一定能修。。等他读取后了重新打开会好点吗？

颜文字自定义点进去之后如果清后台强退会导致所有自定义过的颜文字丢失
这个是这样设计的，因为只有正常退出那个页面的时候才会保存

―

**Comment by yudanhezhongweijie** [comment]
颜文字是存到本地数据库的，强退不会影响他的数据，有没可能是别的原因导致数据被清除了？设置里面也有选项可以手动重置颜文字

**Comment by Tumbleweed1024** [comment]
具体原因不清楚，但是强退确实会导致颜文字数据丢失
________________________________
